default:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: ready-de27
      dataset: abdelrahman_olist_analytics
      threads: 4
      keyfile: /opt/airflow/keys/service-account.json
