default:
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      user: airflow
      password: airflow
      dbname: airflow
      schema: public
      threads: 1
  target: dev