version: 2

############################################################
#  SOURCES: raw BigQuery tables (raw dataset)
############################################################
sources:
  - name: abdelrahman_olist_landing   # <-- your source name
    description: "Raw Olist data imported from the transactional database."
    schema: abdelrahman_olist_landing   # <-- your BigQuery dataset containing the raw tables
    tables:
      - name: orders
        description: "Contains order-level metadata including timestamps and statuses."
      - name: order_items
        description: "Contains item-level data for each order."
      - name: order_payments
        description: "Payment details for each order (type, installments, value)."
      - name: products
        description: "Product-level attributes such as dimensions, weight, and category."
      - name: product_category_name_translation
        description: "Translation between Portuguese and English product category names."
      - name: customers
        description: "Customer information such as location and unique ID."
      - name: sellers
        description: "Seller information including state, city, and zip code prefix."
      - name: geolocation
        description: "Mapping between zip code prefixes and geographic coordinates."
      - name: order_reviews
        description: "Customer reviews and ratings for completed orders."
      - name: leads_qualified
        description: "Marketing qualified leads information."
      - name: leads_closed
        description: "Closed leads and deal information for sales team performance."

############################################################
#  STAGING MODELS
############################################################
models:
  - name: stg_orders
    description: "Cleaned and typed version of the raw orders table."
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: order_purchase_ts
        description: "Timestamp when the order was created."
      - name: order_status
        description: "Current status of the order."

  - name: stg_order_items
    description: "Normalized order item details with numeric price and quantity fields."
    columns:
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_orders')
              field: order_id
      - name: product_id
        tests:
          - not_null
      - name: price
        tests:
          - not_null

  - name: stg_products
    description: "Product attributes enriched with category names."
    columns:
      - name: product_id
        tests:
          - unique
          - not_null

  - name: stg_product_category_name_translation
    description: "Provides English translations for product categories."

  - name: stg_customers
    description: "Customer details including unique IDs and location info."
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_sellers
    description: "Seller information joined to geographic context."
    columns:
      - name: seller_id
        tests:
          - unique
          - not_null

  - name: stg_geolocation
    description: "Geolocation mapping for zip code prefixes."

############################################################
#  CORE FACT MODEL
############################################################
#   - name: fct_order_items
#     description: >
#       Central fact table combining order, order item, customer, product, and seller data.
#       Each row represents a product line within an order.
#     columns:
#       - name: order_id
#         description: "Unique identifier of the order."
#         tests:
#           - not_null
#       - name: order_item_id
#         description: "Line number of the product within the order."
#       - name: customer_id
#         description: "Foreign key to the customers table."
#       - name: product_id
#         description: "Foreign key to the products table."
#       - name: seller_id
#         description: "Foreign key to the sellers table."
#       - name: line_revenue
#         description: "Price × quantity for the order line item."
#       - name: order_purchase_ts
#         description: "Timestamp of purchase, used for monthly aggregations."
#       - name: product_category
#         description: "Readable product category in English."

# ############################################################
# #  ANALYTICS MODELS (dashboard views)
# ############################################################
#   - name: top_customers
#     description: "Top customers ranked by total order revenue."
#     columns:
#       - name: customer_id
#       - name: total_revenue
#         tests:
#           - not_null

#   - name: top_products
#     description: "Top-selling products by total quantity and revenue."
#     columns:
#       - name: product_id
#       - name: total_quantity_sold
#       - name: total_revenue

#   - name: category_revenue
#     description: "Revenue contribution and order counts by product category."
#     columns:
#       - name: product_category
#       - name: total_revenue
#       - name: total_units_sold

#   - name: delivery_time_by_category
#     description: "Average and median delivery times for each category."
#     columns:
#       - name: product_category
#       - name: avg_delivery_days
#       - name: median_delivery_days

#   - name: monthly_metrics
#     description: "Monthly revenue and order trends."
#     columns:
#       - name: month
#       - name: total_orders
#       - name: total_revenue

#   - name: on_time_delivery
#     description: "Share of orders delivered on time versus delayed."
#     columns:
#       - name: delivery_status
#       - name: orders_count

#   - name: seller_order_volumes
#     description: "Ranking of sellers by order count and total revenue."
#     columns:
#       - name: seller_id
#       - name: total_orders
#       - name: total_revenue
